/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfficerIndexRouteImport } from './routes/officer/index'
import { Route as ManagementIndexRouteImport } from './routes/management/index'
import { Route as IppIndexRouteImport } from './routes/ipp/index'
import { Route as ApproverIndexRouteImport } from './routes/approver/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as landingRolesRouteImport } from './routes/(landing)/roles'
import { Route as landingRegisterRouteImport } from './routes/(landing)/register'
import { Route as landingLoginRouteImport } from './routes/(landing)/login'
import { Route as OfficerTasksIndexRouteImport } from './routes/officer/tasks/index'
import { Route as OfficerSlaIndexRouteImport } from './routes/officer/sla/index'
import { Route as OfficerQueueIndexRouteImport } from './routes/officer/queue/index'
import { Route as OfficerQueriesIndexRouteImport } from './routes/officer/queries/index'
import { Route as OfficerNotificationsIndexRouteImport } from './routes/officer/notifications/index'
import { Route as OfficerEscalationsIndexRouteImport } from './routes/officer/escalations/index'
import { Route as ManagementProjectsIndexRouteImport } from './routes/management/projects/index'
import { Route as ManagementAnalyticsIndexRouteImport } from './routes/management/analytics/index'
import { Route as IppTasksIndexRouteImport } from './routes/ipp/tasks/index'
import { Route as IppProfileIndexRouteImport } from './routes/ipp/profile/index'
import { Route as IppOpportunitiesIndexRouteImport } from './routes/ipp/opportunities/index'
import { Route as IppNotificationsIndexRouteImport } from './routes/ipp/notifications/index'
import { Route as IppMilestonesIndexRouteImport } from './routes/ipp/milestones/index'
import { Route as IppApplicationsIndexRouteImport } from './routes/ipp/applications/index'
import { Route as ApproverTasksIndexRouteImport } from './routes/approver/tasks/index'
import { Route as ApproverQueueIndexRouteImport } from './routes/approver/queue/index'
import { Route as ApproverNotificationsIndexRouteImport } from './routes/approver/notifications/index'
import { Route as AdminWorkflowsIndexRouteImport } from './routes/admin/workflows/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminProjectTypesIndexRouteImport } from './routes/admin/project-types/index'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin/opportunities/index'
import { Route as AdminChecklistsIndexRouteImport } from './routes/admin/checklists/index'
import { Route as OfficerProjectsIdRouteImport } from './routes/officer/projects/$id'
import { Route as ManagementProjectsIdRouteImport } from './routes/management/projects/$id'
import { Route as IppProjectsIdRouteImport } from './routes/ipp/projects/$id'
import { Route as IppOpportunitiesIdRouteImport } from './routes/ipp/opportunities/$id'
import { Route as IppApplicationsIdRouteImport } from './routes/ipp/applications/$id'
import { Route as ApproverProjectsIdRouteImport } from './routes/approver/projects/$id'
import { Route as AdminOpportunitiesCreateRouteImport } from './routes/admin/opportunities/create'
import { Route as AdminOpportunitiesIdRouteImport } from './routes/admin/opportunities/$id'
import { Route as OfficerTasksEvaluateOpportunityIdRouteImport } from './routes/officer/tasks/evaluate/$opportunityId'
import { Route as ApproverTasksEvaluateOpportunityIdRouteImport } from './routes/approver/tasks/evaluate/$opportunityId'
import { Route as AdminOpportunitiesEditIdRouteImport } from './routes/admin/opportunities/edit.$id'

const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/management/',
  path: '/management/',
  getParentRoute: () => rootRouteImport,
} as any)
const IppIndexRoute = IppIndexRouteImport.update({
  id: '/ipp/',
  path: '/ipp/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverIndexRoute = ApproverIndexRouteImport.update({
  id: '/approver/',
  path: '/approver/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/(landing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const landingRolesRoute = landingRolesRouteImport.update({
  id: '/(landing)/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const landingRegisterRoute = landingRegisterRouteImport.update({
  id: '/(landing)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const landingLoginRoute = landingLoginRouteImport.update({
  id: '/(landing)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerTasksIndexRoute = OfficerTasksIndexRouteImport.update({
  id: '/officer/tasks/',
  path: '/officer/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerSlaIndexRoute = OfficerSlaIndexRouteImport.update({
  id: '/officer/sla/',
  path: '/officer/sla/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerQueueIndexRoute = OfficerQueueIndexRouteImport.update({
  id: '/officer/queue/',
  path: '/officer/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerQueriesIndexRoute = OfficerQueriesIndexRouteImport.update({
  id: '/officer/queries/',
  path: '/officer/queries/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerNotificationsIndexRoute =
  OfficerNotificationsIndexRouteImport.update({
    id: '/officer/notifications/',
    path: '/officer/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfficerEscalationsIndexRoute = OfficerEscalationsIndexRouteImport.update({
  id: '/officer/escalations/',
  path: '/officer/escalations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementProjectsIndexRoute = ManagementProjectsIndexRouteImport.update({
  id: '/management/projects/',
  path: '/management/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementAnalyticsIndexRoute =
  ManagementAnalyticsIndexRouteImport.update({
    id: '/management/analytics/',
    path: '/management/analytics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IppTasksIndexRoute = IppTasksIndexRouteImport.update({
  id: '/ipp/tasks/',
  path: '/ipp/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const IppProfileIndexRoute = IppProfileIndexRouteImport.update({
  id: '/ipp/profile/',
  path: '/ipp/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const IppOpportunitiesIndexRoute = IppOpportunitiesIndexRouteImport.update({
  id: '/ipp/opportunities/',
  path: '/ipp/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const IppNotificationsIndexRoute = IppNotificationsIndexRouteImport.update({
  id: '/ipp/notifications/',
  path: '/ipp/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const IppMilestonesIndexRoute = IppMilestonesIndexRouteImport.update({
  id: '/ipp/milestones/',
  path: '/ipp/milestones/',
  getParentRoute: () => rootRouteImport,
} as any)
const IppApplicationsIndexRoute = IppApplicationsIndexRouteImport.update({
  id: '/ipp/applications/',
  path: '/ipp/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverTasksIndexRoute = ApproverTasksIndexRouteImport.update({
  id: '/approver/tasks/',
  path: '/approver/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverQueueIndexRoute = ApproverQueueIndexRouteImport.update({
  id: '/approver/queue/',
  path: '/approver/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverNotificationsIndexRoute =
  ApproverNotificationsIndexRouteImport.update({
    id: '/approver/notifications/',
    path: '/approver/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWorkflowsIndexRoute = AdminWorkflowsIndexRouteImport.update({
  id: '/admin/workflows/',
  path: '/admin/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectTypesIndexRoute = AdminProjectTypesIndexRouteImport.update({
  id: '/admin/project-types/',
  path: '/admin/project-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/admin/opportunities/',
  path: '/admin/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChecklistsIndexRoute = AdminChecklistsIndexRouteImport.update({
  id: '/admin/checklists/',
  path: '/admin/checklists/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerProjectsIdRoute = OfficerProjectsIdRouteImport.update({
  id: '/officer/projects/$id',
  path: '/officer/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementProjectsIdRoute = ManagementProjectsIdRouteImport.update({
  id: '/management/projects/$id',
  path: '/management/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IppProjectsIdRoute = IppProjectsIdRouteImport.update({
  id: '/ipp/projects/$id',
  path: '/ipp/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IppOpportunitiesIdRoute = IppOpportunitiesIdRouteImport.update({
  id: '/ipp/opportunities/$id',
  path: '/ipp/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IppApplicationsIdRoute = IppApplicationsIdRouteImport.update({
  id: '/ipp/applications/$id',
  path: '/ipp/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverProjectsIdRoute = ApproverProjectsIdRouteImport.update({
  id: '/approver/projects/$id',
  path: '/approver/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesCreateRoute =
  AdminOpportunitiesCreateRouteImport.update({
    id: '/admin/opportunities/create',
    path: '/admin/opportunities/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOpportunitiesIdRoute = AdminOpportunitiesIdRouteImport.update({
  id: '/admin/opportunities/$id',
  path: '/admin/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerTasksEvaluateOpportunityIdRoute =
  OfficerTasksEvaluateOpportunityIdRouteImport.update({
    id: '/officer/tasks/evaluate/$opportunityId',
    path: '/officer/tasks/evaluate/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApproverTasksEvaluateOpportunityIdRoute =
  ApproverTasksEvaluateOpportunityIdRouteImport.update({
    id: '/approver/tasks/evaluate/$opportunityId',
    path: '/approver/tasks/evaluate/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOpportunitiesEditIdRoute =
  AdminOpportunitiesEditIdRouteImport.update({
    id: '/admin/opportunities/edit/$id',
    path: '/admin/opportunities/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof landingLoginRoute
  '/register': typeof landingRegisterRoute
  '/roles': typeof landingRolesRoute
  '/': typeof landingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/approver/': typeof ApproverIndexRoute
  '/ipp/': typeof IppIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/admin/opportunities/$id': typeof AdminOpportunitiesIdRoute
  '/admin/opportunities/create': typeof AdminOpportunitiesCreateRoute
  '/approver/projects/$id': typeof ApproverProjectsIdRoute
  '/ipp/applications/$id': typeof IppApplicationsIdRoute
  '/ipp/opportunities/$id': typeof IppOpportunitiesIdRoute
  '/ipp/projects/$id': typeof IppProjectsIdRoute
  '/management/projects/$id': typeof ManagementProjectsIdRoute
  '/officer/projects/$id': typeof OfficerProjectsIdRoute
  '/admin/checklists/': typeof AdminChecklistsIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/project-types/': typeof AdminProjectTypesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/workflows/': typeof AdminWorkflowsIndexRoute
  '/approver/notifications/': typeof ApproverNotificationsIndexRoute
  '/approver/queue/': typeof ApproverQueueIndexRoute
  '/approver/tasks/': typeof ApproverTasksIndexRoute
  '/ipp/applications/': typeof IppApplicationsIndexRoute
  '/ipp/milestones/': typeof IppMilestonesIndexRoute
  '/ipp/notifications/': typeof IppNotificationsIndexRoute
  '/ipp/opportunities/': typeof IppOpportunitiesIndexRoute
  '/ipp/profile/': typeof IppProfileIndexRoute
  '/ipp/tasks/': typeof IppTasksIndexRoute
  '/management/analytics/': typeof ManagementAnalyticsIndexRoute
  '/management/projects/': typeof ManagementProjectsIndexRoute
  '/officer/escalations/': typeof OfficerEscalationsIndexRoute
  '/officer/notifications/': typeof OfficerNotificationsIndexRoute
  '/officer/queries/': typeof OfficerQueriesIndexRoute
  '/officer/queue/': typeof OfficerQueueIndexRoute
  '/officer/sla/': typeof OfficerSlaIndexRoute
  '/officer/tasks/': typeof OfficerTasksIndexRoute
  '/admin/opportunities/edit/$id': typeof AdminOpportunitiesEditIdRoute
  '/approver/tasks/evaluate/$opportunityId': typeof ApproverTasksEvaluateOpportunityIdRoute
  '/officer/tasks/evaluate/$opportunityId': typeof OfficerTasksEvaluateOpportunityIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof landingLoginRoute
  '/register': typeof landingRegisterRoute
  '/roles': typeof landingRolesRoute
  '/': typeof landingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/approver': typeof ApproverIndexRoute
  '/ipp': typeof IppIndexRoute
  '/management': typeof ManagementIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/admin/opportunities/$id': typeof AdminOpportunitiesIdRoute
  '/admin/opportunities/create': typeof AdminOpportunitiesCreateRoute
  '/approver/projects/$id': typeof ApproverProjectsIdRoute
  '/ipp/applications/$id': typeof IppApplicationsIdRoute
  '/ipp/opportunities/$id': typeof IppOpportunitiesIdRoute
  '/ipp/projects/$id': typeof IppProjectsIdRoute
  '/management/projects/$id': typeof ManagementProjectsIdRoute
  '/officer/projects/$id': typeof OfficerProjectsIdRoute
  '/admin/checklists': typeof AdminChecklistsIndexRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
  '/admin/project-types': typeof AdminProjectTypesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/workflows': typeof AdminWorkflowsIndexRoute
  '/approver/notifications': typeof ApproverNotificationsIndexRoute
  '/approver/queue': typeof ApproverQueueIndexRoute
  '/approver/tasks': typeof ApproverTasksIndexRoute
  '/ipp/applications': typeof IppApplicationsIndexRoute
  '/ipp/milestones': typeof IppMilestonesIndexRoute
  '/ipp/notifications': typeof IppNotificationsIndexRoute
  '/ipp/opportunities': typeof IppOpportunitiesIndexRoute
  '/ipp/profile': typeof IppProfileIndexRoute
  '/ipp/tasks': typeof IppTasksIndexRoute
  '/management/analytics': typeof ManagementAnalyticsIndexRoute
  '/management/projects': typeof ManagementProjectsIndexRoute
  '/officer/escalations': typeof OfficerEscalationsIndexRoute
  '/officer/notifications': typeof OfficerNotificationsIndexRoute
  '/officer/queries': typeof OfficerQueriesIndexRoute
  '/officer/queue': typeof OfficerQueueIndexRoute
  '/officer/sla': typeof OfficerSlaIndexRoute
  '/officer/tasks': typeof OfficerTasksIndexRoute
  '/admin/opportunities/edit/$id': typeof AdminOpportunitiesEditIdRoute
  '/approver/tasks/evaluate/$opportunityId': typeof ApproverTasksEvaluateOpportunityIdRoute
  '/officer/tasks/evaluate/$opportunityId': typeof OfficerTasksEvaluateOpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(landing)/login': typeof landingLoginRoute
  '/(landing)/register': typeof landingRegisterRoute
  '/(landing)/roles': typeof landingRolesRoute
  '/(landing)/': typeof landingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/approver/': typeof ApproverIndexRoute
  '/ipp/': typeof IppIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/admin/opportunities/$id': typeof AdminOpportunitiesIdRoute
  '/admin/opportunities/create': typeof AdminOpportunitiesCreateRoute
  '/approver/projects/$id': typeof ApproverProjectsIdRoute
  '/ipp/applications/$id': typeof IppApplicationsIdRoute
  '/ipp/opportunities/$id': typeof IppOpportunitiesIdRoute
  '/ipp/projects/$id': typeof IppProjectsIdRoute
  '/management/projects/$id': typeof ManagementProjectsIdRoute
  '/officer/projects/$id': typeof OfficerProjectsIdRoute
  '/admin/checklists/': typeof AdminChecklistsIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/project-types/': typeof AdminProjectTypesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/workflows/': typeof AdminWorkflowsIndexRoute
  '/approver/notifications/': typeof ApproverNotificationsIndexRoute
  '/approver/queue/': typeof ApproverQueueIndexRoute
  '/approver/tasks/': typeof ApproverTasksIndexRoute
  '/ipp/applications/': typeof IppApplicationsIndexRoute
  '/ipp/milestones/': typeof IppMilestonesIndexRoute
  '/ipp/notifications/': typeof IppNotificationsIndexRoute
  '/ipp/opportunities/': typeof IppOpportunitiesIndexRoute
  '/ipp/profile/': typeof IppProfileIndexRoute
  '/ipp/tasks/': typeof IppTasksIndexRoute
  '/management/analytics/': typeof ManagementAnalyticsIndexRoute
  '/management/projects/': typeof ManagementProjectsIndexRoute
  '/officer/escalations/': typeof OfficerEscalationsIndexRoute
  '/officer/notifications/': typeof OfficerNotificationsIndexRoute
  '/officer/queries/': typeof OfficerQueriesIndexRoute
  '/officer/queue/': typeof OfficerQueueIndexRoute
  '/officer/sla/': typeof OfficerSlaIndexRoute
  '/officer/tasks/': typeof OfficerTasksIndexRoute
  '/admin/opportunities/edit/$id': typeof AdminOpportunitiesEditIdRoute
  '/approver/tasks/evaluate/$opportunityId': typeof ApproverTasksEvaluateOpportunityIdRoute
  '/officer/tasks/evaluate/$opportunityId': typeof OfficerTasksEvaluateOpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/roles'
    | '/'
    | '/admin/'
    | '/approver/'
    | '/ipp/'
    | '/management/'
    | '/officer/'
    | '/admin/opportunities/$id'
    | '/admin/opportunities/create'
    | '/approver/projects/$id'
    | '/ipp/applications/$id'
    | '/ipp/opportunities/$id'
    | '/ipp/projects/$id'
    | '/management/projects/$id'
    | '/officer/projects/$id'
    | '/admin/checklists/'
    | '/admin/opportunities/'
    | '/admin/project-types/'
    | '/admin/users/'
    | '/admin/workflows/'
    | '/approver/notifications/'
    | '/approver/queue/'
    | '/approver/tasks/'
    | '/ipp/applications/'
    | '/ipp/milestones/'
    | '/ipp/notifications/'
    | '/ipp/opportunities/'
    | '/ipp/profile/'
    | '/ipp/tasks/'
    | '/management/analytics/'
    | '/management/projects/'
    | '/officer/escalations/'
    | '/officer/notifications/'
    | '/officer/queries/'
    | '/officer/queue/'
    | '/officer/sla/'
    | '/officer/tasks/'
    | '/admin/opportunities/edit/$id'
    | '/approver/tasks/evaluate/$opportunityId'
    | '/officer/tasks/evaluate/$opportunityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/roles'
    | '/'
    | '/admin'
    | '/approver'
    | '/ipp'
    | '/management'
    | '/officer'
    | '/admin/opportunities/$id'
    | '/admin/opportunities/create'
    | '/approver/projects/$id'
    | '/ipp/applications/$id'
    | '/ipp/opportunities/$id'
    | '/ipp/projects/$id'
    | '/management/projects/$id'
    | '/officer/projects/$id'
    | '/admin/checklists'
    | '/admin/opportunities'
    | '/admin/project-types'
    | '/admin/users'
    | '/admin/workflows'
    | '/approver/notifications'
    | '/approver/queue'
    | '/approver/tasks'
    | '/ipp/applications'
    | '/ipp/milestones'
    | '/ipp/notifications'
    | '/ipp/opportunities'
    | '/ipp/profile'
    | '/ipp/tasks'
    | '/management/analytics'
    | '/management/projects'
    | '/officer/escalations'
    | '/officer/notifications'
    | '/officer/queries'
    | '/officer/queue'
    | '/officer/sla'
    | '/officer/tasks'
    | '/admin/opportunities/edit/$id'
    | '/approver/tasks/evaluate/$opportunityId'
    | '/officer/tasks/evaluate/$opportunityId'
  id:
    | '__root__'
    | '/(landing)/login'
    | '/(landing)/register'
    | '/(landing)/roles'
    | '/(landing)/'
    | '/admin/'
    | '/approver/'
    | '/ipp/'
    | '/management/'
    | '/officer/'
    | '/admin/opportunities/$id'
    | '/admin/opportunities/create'
    | '/approver/projects/$id'
    | '/ipp/applications/$id'
    | '/ipp/opportunities/$id'
    | '/ipp/projects/$id'
    | '/management/projects/$id'
    | '/officer/projects/$id'
    | '/admin/checklists/'
    | '/admin/opportunities/'
    | '/admin/project-types/'
    | '/admin/users/'
    | '/admin/workflows/'
    | '/approver/notifications/'
    | '/approver/queue/'
    | '/approver/tasks/'
    | '/ipp/applications/'
    | '/ipp/milestones/'
    | '/ipp/notifications/'
    | '/ipp/opportunities/'
    | '/ipp/profile/'
    | '/ipp/tasks/'
    | '/management/analytics/'
    | '/management/projects/'
    | '/officer/escalations/'
    | '/officer/notifications/'
    | '/officer/queries/'
    | '/officer/queue/'
    | '/officer/sla/'
    | '/officer/tasks/'
    | '/admin/opportunities/edit/$id'
    | '/approver/tasks/evaluate/$opportunityId'
    | '/officer/tasks/evaluate/$opportunityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  landingLoginRoute: typeof landingLoginRoute
  landingRegisterRoute: typeof landingRegisterRoute
  landingRolesRoute: typeof landingRolesRoute
  landingIndexRoute: typeof landingIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApproverIndexRoute: typeof ApproverIndexRoute
  IppIndexRoute: typeof IppIndexRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  AdminOpportunitiesIdRoute: typeof AdminOpportunitiesIdRoute
  AdminOpportunitiesCreateRoute: typeof AdminOpportunitiesCreateRoute
  ApproverProjectsIdRoute: typeof ApproverProjectsIdRoute
  IppApplicationsIdRoute: typeof IppApplicationsIdRoute
  IppOpportunitiesIdRoute: typeof IppOpportunitiesIdRoute
  IppProjectsIdRoute: typeof IppProjectsIdRoute
  ManagementProjectsIdRoute: typeof ManagementProjectsIdRoute
  OfficerProjectsIdRoute: typeof OfficerProjectsIdRoute
  AdminChecklistsIndexRoute: typeof AdminChecklistsIndexRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
  AdminProjectTypesIndexRoute: typeof AdminProjectTypesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWorkflowsIndexRoute: typeof AdminWorkflowsIndexRoute
  ApproverNotificationsIndexRoute: typeof ApproverNotificationsIndexRoute
  ApproverQueueIndexRoute: typeof ApproverQueueIndexRoute
  ApproverTasksIndexRoute: typeof ApproverTasksIndexRoute
  IppApplicationsIndexRoute: typeof IppApplicationsIndexRoute
  IppMilestonesIndexRoute: typeof IppMilestonesIndexRoute
  IppNotificationsIndexRoute: typeof IppNotificationsIndexRoute
  IppOpportunitiesIndexRoute: typeof IppOpportunitiesIndexRoute
  IppProfileIndexRoute: typeof IppProfileIndexRoute
  IppTasksIndexRoute: typeof IppTasksIndexRoute
  ManagementAnalyticsIndexRoute: typeof ManagementAnalyticsIndexRoute
  ManagementProjectsIndexRoute: typeof ManagementProjectsIndexRoute
  OfficerEscalationsIndexRoute: typeof OfficerEscalationsIndexRoute
  OfficerNotificationsIndexRoute: typeof OfficerNotificationsIndexRoute
  OfficerQueriesIndexRoute: typeof OfficerQueriesIndexRoute
  OfficerQueueIndexRoute: typeof OfficerQueueIndexRoute
  OfficerSlaIndexRoute: typeof OfficerSlaIndexRoute
  OfficerTasksIndexRoute: typeof OfficerTasksIndexRoute
  AdminOpportunitiesEditIdRoute: typeof AdminOpportunitiesEditIdRoute
  ApproverTasksEvaluateOpportunityIdRoute: typeof ApproverTasksEvaluateOpportunityIdRoute
  OfficerTasksEvaluateOpportunityIdRoute: typeof OfficerTasksEvaluateOpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/officer/': {
      id: '/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/': {
      id: '/management/'
      path: '/management'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/': {
      id: '/ipp/'
      path: '/ipp'
      fullPath: '/ipp/'
      preLoaderRoute: typeof IppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver/': {
      id: '/approver/'
      path: '/approver'
      fullPath: '/approver/'
      preLoaderRoute: typeof ApproverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/roles': {
      id: '/(landing)/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof landingRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/register': {
      id: '/(landing)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof landingRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/login': {
      id: '/(landing)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof landingLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/tasks/': {
      id: '/officer/tasks/'
      path: '/officer/tasks'
      fullPath: '/officer/tasks/'
      preLoaderRoute: typeof OfficerTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/sla/': {
      id: '/officer/sla/'
      path: '/officer/sla'
      fullPath: '/officer/sla/'
      preLoaderRoute: typeof OfficerSlaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/queue/': {
      id: '/officer/queue/'
      path: '/officer/queue'
      fullPath: '/officer/queue/'
      preLoaderRoute: typeof OfficerQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/queries/': {
      id: '/officer/queries/'
      path: '/officer/queries'
      fullPath: '/officer/queries/'
      preLoaderRoute: typeof OfficerQueriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/notifications/': {
      id: '/officer/notifications/'
      path: '/officer/notifications'
      fullPath: '/officer/notifications/'
      preLoaderRoute: typeof OfficerNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/escalations/': {
      id: '/officer/escalations/'
      path: '/officer/escalations'
      fullPath: '/officer/escalations/'
      preLoaderRoute: typeof OfficerEscalationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/projects/': {
      id: '/management/projects/'
      path: '/management/projects'
      fullPath: '/management/projects/'
      preLoaderRoute: typeof ManagementProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/analytics/': {
      id: '/management/analytics/'
      path: '/management/analytics'
      fullPath: '/management/analytics/'
      preLoaderRoute: typeof ManagementAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/tasks/': {
      id: '/ipp/tasks/'
      path: '/ipp/tasks'
      fullPath: '/ipp/tasks/'
      preLoaderRoute: typeof IppTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/profile/': {
      id: '/ipp/profile/'
      path: '/ipp/profile'
      fullPath: '/ipp/profile/'
      preLoaderRoute: typeof IppProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/opportunities/': {
      id: '/ipp/opportunities/'
      path: '/ipp/opportunities'
      fullPath: '/ipp/opportunities/'
      preLoaderRoute: typeof IppOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/notifications/': {
      id: '/ipp/notifications/'
      path: '/ipp/notifications'
      fullPath: '/ipp/notifications/'
      preLoaderRoute: typeof IppNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/milestones/': {
      id: '/ipp/milestones/'
      path: '/ipp/milestones'
      fullPath: '/ipp/milestones/'
      preLoaderRoute: typeof IppMilestonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/applications/': {
      id: '/ipp/applications/'
      path: '/ipp/applications'
      fullPath: '/ipp/applications/'
      preLoaderRoute: typeof IppApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver/tasks/': {
      id: '/approver/tasks/'
      path: '/approver/tasks'
      fullPath: '/approver/tasks/'
      preLoaderRoute: typeof ApproverTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver/queue/': {
      id: '/approver/queue/'
      path: '/approver/queue'
      fullPath: '/approver/queue/'
      preLoaderRoute: typeof ApproverQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver/notifications/': {
      id: '/approver/notifications/'
      path: '/approver/notifications'
      fullPath: '/approver/notifications/'
      preLoaderRoute: typeof ApproverNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflows/': {
      id: '/admin/workflows/'
      path: '/admin/workflows'
      fullPath: '/admin/workflows/'
      preLoaderRoute: typeof AdminWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/project-types/': {
      id: '/admin/project-types/'
      path: '/admin/project-types'
      fullPath: '/admin/project-types/'
      preLoaderRoute: typeof AdminProjectTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/admin/opportunities'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklists/': {
      id: '/admin/checklists/'
      path: '/admin/checklists'
      fullPath: '/admin/checklists/'
      preLoaderRoute: typeof AdminChecklistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/projects/$id': {
      id: '/officer/projects/$id'
      path: '/officer/projects/$id'
      fullPath: '/officer/projects/$id'
      preLoaderRoute: typeof OfficerProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/projects/$id': {
      id: '/management/projects/$id'
      path: '/management/projects/$id'
      fullPath: '/management/projects/$id'
      preLoaderRoute: typeof ManagementProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/projects/$id': {
      id: '/ipp/projects/$id'
      path: '/ipp/projects/$id'
      fullPath: '/ipp/projects/$id'
      preLoaderRoute: typeof IppProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/opportunities/$id': {
      id: '/ipp/opportunities/$id'
      path: '/ipp/opportunities/$id'
      fullPath: '/ipp/opportunities/$id'
      preLoaderRoute: typeof IppOpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipp/applications/$id': {
      id: '/ipp/applications/$id'
      path: '/ipp/applications/$id'
      fullPath: '/ipp/applications/$id'
      preLoaderRoute: typeof IppApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver/projects/$id': {
      id: '/approver/projects/$id'
      path: '/approver/projects/$id'
      fullPath: '/approver/projects/$id'
      preLoaderRoute: typeof ApproverProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/create': {
      id: '/admin/opportunities/create'
      path: '/admin/opportunities/create'
      fullPath: '/admin/opportunities/create'
      preLoaderRoute: typeof AdminOpportunitiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/$id': {
      id: '/admin/opportunities/$id'
      path: '/admin/opportunities/$id'
      fullPath: '/admin/opportunities/$id'
      preLoaderRoute: typeof AdminOpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/tasks/evaluate/$opportunityId': {
      id: '/officer/tasks/evaluate/$opportunityId'
      path: '/officer/tasks/evaluate/$opportunityId'
      fullPath: '/officer/tasks/evaluate/$opportunityId'
      preLoaderRoute: typeof OfficerTasksEvaluateOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver/tasks/evaluate/$opportunityId': {
      id: '/approver/tasks/evaluate/$opportunityId'
      path: '/approver/tasks/evaluate/$opportunityId'
      fullPath: '/approver/tasks/evaluate/$opportunityId'
      preLoaderRoute: typeof ApproverTasksEvaluateOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/edit/$id': {
      id: '/admin/opportunities/edit/$id'
      path: '/admin/opportunities/edit/$id'
      fullPath: '/admin/opportunities/edit/$id'
      preLoaderRoute: typeof AdminOpportunitiesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  landingLoginRoute: landingLoginRoute,
  landingRegisterRoute: landingRegisterRoute,
  landingRolesRoute: landingRolesRoute,
  landingIndexRoute: landingIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApproverIndexRoute: ApproverIndexRoute,
  IppIndexRoute: IppIndexRoute,
  ManagementIndexRoute: ManagementIndexRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  AdminOpportunitiesIdRoute: AdminOpportunitiesIdRoute,
  AdminOpportunitiesCreateRoute: AdminOpportunitiesCreateRoute,
  ApproverProjectsIdRoute: ApproverProjectsIdRoute,
  IppApplicationsIdRoute: IppApplicationsIdRoute,
  IppOpportunitiesIdRoute: IppOpportunitiesIdRoute,
  IppProjectsIdRoute: IppProjectsIdRoute,
  ManagementProjectsIdRoute: ManagementProjectsIdRoute,
  OfficerProjectsIdRoute: OfficerProjectsIdRoute,
  AdminChecklistsIndexRoute: AdminChecklistsIndexRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
  AdminProjectTypesIndexRoute: AdminProjectTypesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWorkflowsIndexRoute: AdminWorkflowsIndexRoute,
  ApproverNotificationsIndexRoute: ApproverNotificationsIndexRoute,
  ApproverQueueIndexRoute: ApproverQueueIndexRoute,
  ApproverTasksIndexRoute: ApproverTasksIndexRoute,
  IppApplicationsIndexRoute: IppApplicationsIndexRoute,
  IppMilestonesIndexRoute: IppMilestonesIndexRoute,
  IppNotificationsIndexRoute: IppNotificationsIndexRoute,
  IppOpportunitiesIndexRoute: IppOpportunitiesIndexRoute,
  IppProfileIndexRoute: IppProfileIndexRoute,
  IppTasksIndexRoute: IppTasksIndexRoute,
  ManagementAnalyticsIndexRoute: ManagementAnalyticsIndexRoute,
  ManagementProjectsIndexRoute: ManagementProjectsIndexRoute,
  OfficerEscalationsIndexRoute: OfficerEscalationsIndexRoute,
  OfficerNotificationsIndexRoute: OfficerNotificationsIndexRoute,
  OfficerQueriesIndexRoute: OfficerQueriesIndexRoute,
  OfficerQueueIndexRoute: OfficerQueueIndexRoute,
  OfficerSlaIndexRoute: OfficerSlaIndexRoute,
  OfficerTasksIndexRoute: OfficerTasksIndexRoute,
  AdminOpportunitiesEditIdRoute: AdminOpportunitiesEditIdRoute,
  ApproverTasksEvaluateOpportunityIdRoute:
    ApproverTasksEvaluateOpportunityIdRoute,
  OfficerTasksEvaluateOpportunityIdRoute:
    OfficerTasksEvaluateOpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
