import type { Bill, Budget, BudgetAllocation, BudgetAdjustment, BudgetReservation, Receipt, ReceiptCancellationRequest, ReconciliationBatch, Task, AuditLog } from './types';

const today = new Date();
const iso = (offsetDays = 0, hours = 9) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hours, 30, 0, 0);
  return d.toISOString();
};

export const initialBills: Bill[] = [
  {
    billId: 'BILL-2026-0001',
    billType: 'TA/DA Reimbursement',
    description: 'Travel allowance for academic conference at AIIMS Delhi',
    amount: 45200,
    panNumber: 'ABCDE1234F',
    payeeName: 'Dr. Anil Kumar',
    bankAccount: '12345678901',
    ifsc: 'SBIN0001234',
    bankName: 'State Bank of India',
    budgetHead: 'TA/DA',
    department: 'Department of Pharmacology',
    status: 'Submitted',
    createdBy: 'rajesh.kumar',
    createdByRole: 'Creator',
    createdAt: iso(-3, 11),
    updatedAt: iso(-1, 14),
    attachments: [
      { name: 'travel-bills.pdf', size: '420 KB' },
      { name: 'conference-invite.pdf', size: '180 KB' },
    ],
    comments: [
      { id: 'c1', user: 'rajesh.kumar', role: 'Creator', message: 'All travel receipts attached.', at: iso(-3, 11) },
    ],
    history: [
      { id: 'h1', user: 'rajesh.kumar', role: 'Creator', action: 'Created Bill', at: iso(-3, 10) },
      { id: 'h2', user: 'rajesh.kumar', role: 'Creator', action: 'Submitted for Verification', at: iso(-3, 11) },
    ],
  },
  {
    billId: 'BILL-2026-0002',
    billType: 'Vendor Payment',
    description: 'Lab equipment purchase – Anatomy Department',
    amount: 235000,
    panNumber: 'XYZAB5678C',
    payeeName: 'MediLabs Pvt Ltd',
    bankAccount: '98765432101',
    ifsc: 'HDFC0000456',
    bankName: 'HDFC Bank',
    budgetHead: 'Equipment',
    department: 'Department of Anatomy',
    status: 'Verification Approved',
    createdBy: 'sunita.rao',
    createdByRole: 'Creator',
    createdAt: iso(-5, 10),
    updatedAt: iso(-2, 16),
    attachments: [
      { name: 'invoice-1284.pdf', size: '310 KB' },
      { name: 'gst-cert.pdf', size: '95 KB' },
    ],
    comments: [
      { id: 'c2', user: 'sunita.rao', role: 'Creator', message: 'PO #4521 referenced.', at: iso(-5, 10) },
      { id: 'c3', user: 'mohan.v', role: 'Verifier', message: 'Documents verified, GST valid.', at: iso(-2, 16) },
    ],
    history: [
      { id: 'h3', user: 'sunita.rao', role: 'Creator', action: 'Created Bill', at: iso(-5, 10) },
      { id: 'h4', user: 'sunita.rao', role: 'Creator', action: 'Submitted for Verification', at: iso(-5, 11) },
      { id: 'h5', user: 'mohan.v', role: 'Verifier', action: 'Verified & Forwarded to Finance', at: iso(-2, 16) },
    ],
  },
  {
    billId: 'BILL-2026-0003',
    billType: 'Remuneration',
    description: 'Guest faculty payment – External Examiners',
    amount: 78000,
    panNumber: 'PQRST9012D',
    payeeName: 'Prof. Lata Iyer',
    bankAccount: '55667788990',
    ifsc: 'ICIC0001234',
    bankName: 'ICICI Bank',
    budgetHead: 'Remuneration',
    department: 'Examination Section',
    status: 'Approved',
    createdBy: 'meena.s',
    createdByRole: 'Creator',
    createdAt: iso(-7, 9),
    updatedAt: iso(-1, 11),
    attachments: [{ name: 'faculty-claim.pdf', size: '210 KB' }],
    comments: [
      { id: 'c4', user: 'meena.s', role: 'Creator', message: 'Claim form attached.', at: iso(-7, 9) },
    ],
    history: [
      { id: 'h6', user: 'meena.s', role: 'Creator', action: 'Submitted', at: iso(-7, 9) },
      { id: 'h7', user: 'mohan.v', role: 'Verifier', action: 'Verified', at: iso(-5, 12) },
      { id: 'h8', user: 'priya.f', role: 'Finance', action: 'Approved', at: iso(-1, 11), detail: 'Within budget' },
    ],
  },
  {
    billId: 'BILL-2026-0004',
    billType: 'Honorarium',
    description: 'Honorarium for visiting examiner panel',
    amount: 12000,
    panNumber: 'LMNOP3456E',
    payeeName: 'Dr. Kavita Joshi',
    bankAccount: '11223344556',
    ifsc: 'AXIS0000222',
    bankName: 'Axis Bank',
    budgetHead: 'Honorarium',
    department: 'Examination Section',
    status: 'Paid',
    createdBy: 'meena.s',
    createdByRole: 'Creator',
    createdAt: iso(-15, 9),
    updatedAt: iso(-2, 12),
    attachments: [{ name: 'honorarium-form.pdf', size: '140 KB' }],
    comments: [],
    history: [
      { id: 'h9', user: 'meena.s', role: 'Creator', action: 'Submitted', at: iso(-15, 9) },
      { id: 'h10', user: 'mohan.v', role: 'Verifier', action: 'Verified', at: iso(-12, 10) },
      { id: 'h11', user: 'priya.f', role: 'Finance', action: 'Approved', at: iso(-8, 14) },
      { id: 'h12', user: 'arvind.p', role: 'Payment', action: 'Paid via NEFT', at: iso(-2, 12) },
    ],
    paymentMode: 'NEFT',
    paymentRef: 'NEFT-2026-00451',
    paidAt: iso(-2, 12),
  },
  {
    billId: 'BILL-2026-0005',
    billType: 'Utility Bill',
    description: 'Quarterly electricity bill – Main campus',
    amount: 184500,
    panNumber: 'BESCM5678Q',
    payeeName: 'BESCOM',
    bankAccount: '00112233445',
    ifsc: 'CNRB0001111',
    bankName: 'Canara Bank',
    budgetHead: 'Utilities',
    department: 'Estate & Maintenance',
    status: 'Draft',
    createdBy: 'rajesh.kumar',
    createdByRole: 'Creator',
    createdAt: iso(-1, 9),
    updatedAt: iso(-1, 9),
    attachments: [{ name: 'bescom-q4.pdf', size: '90 KB' }],
    comments: [],
    history: [
      { id: 'h13', user: 'rajesh.kumar', role: 'Creator', action: 'Created Bill', at: iso(-1, 9) },
    ],
  },
  {
    billId: 'BILL-2026-0006',
    billType: 'Vendor Payment',
    description: 'AMC – Library management system renewal',
    amount: 92500,
    panNumber: 'AMCSE1122Z',
    payeeName: 'EduSoft Solutions',
    bankAccount: '99887766554',
    ifsc: 'YESB0001234',
    bankName: 'Yes Bank',
    budgetHead: 'AMC',
    department: 'Central Library',
    status: 'Sent Back',
    createdBy: 'sunita.rao',
    createdByRole: 'Creator',
    createdAt: iso(-4, 10),
    updatedAt: iso(-1, 15),
    attachments: [{ name: 'amc-quote.pdf', size: '270 KB' }],
    comments: [
      { id: 'c5', user: 'mohan.v', role: 'Verifier', message: 'GSTIN missing on invoice. Please attach updated copy.', at: iso(-1, 15) },
    ],
    history: [
      { id: 'h14', user: 'sunita.rao', role: 'Creator', action: 'Submitted', at: iso(-4, 10) },
      { id: 'h15', user: 'mohan.v', role: 'Verifier', action: 'Sent Back', at: iso(-1, 15), detail: 'GSTIN missing on invoice' },
    ],
  },
];

export const initialTasks: Task[] = [
  {
    taskId: 'TASK-001', subjectType: 'Bill',
    billId: 'BILL-2026-0001',
    assignedToRole: 'Verifier',
    status: 'Pending',
    actionRequired: 'Verify Bill',
    createdAt: iso(-3, 11),
    updatedAt: iso(-3, 11),
  },
  {
    taskId: 'TASK-002', subjectType: 'Bill',
    billId: 'BILL-2026-0002',
    assignedToRole: 'Finance',
    status: 'Pending',
    actionRequired: 'Approve Bill',
    createdAt: iso(-2, 16),
    updatedAt: iso(-2, 16),
  },
  {
    taskId: 'TASK-003', subjectType: 'Bill',
    billId: 'BILL-2026-0003',
    assignedToRole: 'Payment',
    status: 'Pending',
    actionRequired: 'Process Payment',
    createdAt: iso(-1, 11),
    updatedAt: iso(-1, 11),
  },
  {
    taskId: 'TASK-004', subjectType: 'Bill',
    billId: 'BILL-2026-0006',
    assignedToRole: 'Creator',
    status: 'Pending',
    actionRequired: 'Edit & Resubmit',
    createdAt: iso(-1, 15),
    updatedAt: iso(-1, 15),
  },
  // Budget tasks — generated by the workflow on submit / forward / send-back
  {
    taskId: 'TASK-B01', subjectType: 'Budget',
    budgetId: 'BUD-2026-002',
    assignedToRole: 'Verifier',
    status: 'Pending',
    actionRequired: 'Verify Budget',
    createdAt: iso(-2, 14),
    updatedAt: iso(-2, 14),
  },
  {
    taskId: 'TASK-B02', subjectType: 'Budget',
    budgetId: 'BUD-2026-003',
    assignedToRole: 'Approver',
    status: 'Pending',
    actionRequired: 'Approve Budget',
    createdAt: iso(-5, 16),
    updatedAt: iso(-5, 16),
  },
  {
    taskId: 'TASK-B03', subjectType: 'Budget',
    budgetId: 'BUD-2026-004',
    assignedToRole: 'Creator',
    status: 'Pending',
    actionRequired: 'Edit & Resubmit Budget',
    createdAt: iso(-1, 11),
    updatedAt: iso(-1, 11),
  },
  // Receipt tasks — generated by the workflow
  {
    taskId: 'TASK-R01', subjectType: 'Receipt',
    receiptId: 'RCPT-001',
    assignedToRole: 'Verifier',
    status: 'Pending',
    actionRequired: 'Verify Receipt',
    createdAt: iso(-1, 11),
    updatedAt: iso(-1, 11),
  },
  {
    taskId: 'TASK-R02', subjectType: 'Receipt',
    receiptId: 'RCPT-002',
    assignedToRole: 'Approver',
    status: 'Pending',
    actionRequired: 'Approve Receipt',
    createdAt: iso(-2, 16),
    updatedAt: iso(-2, 16),
  },
  {
    taskId: 'TASK-R03', subjectType: 'Receipt',
    receiptId: 'RCPT-004',
    assignedToRole: 'Verifier',
    status: 'Pending',
    actionRequired: 'Verify Receipt',
    createdAt: iso(-2, 16),
    updatedAt: iso(-2, 16),
  },
  {
    taskId: 'TASK-R04', subjectType: 'Receipt',
    receiptId: 'RCPT-005',
    assignedToRole: 'Creator',
    status: 'Pending',
    actionRequired: 'Edit & Resubmit Receipt',
    createdAt: iso(-1, 14),
    updatedAt: iso(-1, 14),
  },
  // Approved by Approver — Finance Officer must review
  {
    taskId: 'TASK-R05', subjectType: 'Receipt',
    receiptId: 'RCPT-007',
    assignedToRole: 'Finance',
    status: 'Pending',
    actionRequired: 'Review Receipt',
    createdAt: iso(-2, 14),
    updatedAt: iso(-2, 14),
  },
];

/* ============== Budgets — rich seed across statuses ============== */

const lastYearTotals: Record<string, number> = {
  'TA/DA': 4200000,
  'Remuneration': 11200000,
  'Honorarium': 2300000,
  'Equipment': 16500000,
  'AMC': 3300000,
  'Utilities': 7800000,
  'Miscellaneous': 1400000,
};

export const initialBudgets: Budget[] = [
  {
    id: 'BUD-2026-001',
    fy: 'FY 2025-26',
    name: 'University Annual Operating Budget',
    entityType: 'University',
    entityName: 'RGUHS HQ',
    version: 1,
    status: 'Approved',
    heads: [
      { id: 'h-tada',  name: 'TA/DA',          allocated: 5000000,  utilized: 1850000, reserved: 220000, lastYearAmount: lastYearTotals['TA/DA'] },
      { id: 'h-rem',   name: 'Remuneration',   allocated: 12000000, utilized: 8200000, reserved: 450000, lastYearAmount: lastYearTotals['Remuneration'] },
      { id: 'h-hon',   name: 'Honorarium',     allocated: 2500000,  utilized: 2150000, reserved: 0,      lastYearAmount: lastYearTotals['Honorarium'] },
      { id: 'h-eq',    name: 'Equipment',      allocated: 18000000, utilized: 9450000, reserved: 1200000, lastYearAmount: lastYearTotals['Equipment'] },
      { id: 'h-amc',   name: 'AMC',            allocated: 3500000,  utilized: 2870000, reserved: 92500,  lastYearAmount: lastYearTotals['AMC'] },
      { id: 'h-util',  name: 'Utilities',      allocated: 8000000,  utilized: 5320000, reserved: 184500, lastYearAmount: lastYearTotals['Utilities'] },
      { id: 'h-mis',   name: 'Miscellaneous',  allocated: 1500000,  utilized: 460000,  reserved: 0,      lastYearAmount: lastYearTotals['Miscellaneous'] },
    ],
    createdBy: 'rajesh.kumar',
    createdAt: iso(-180, 10),
    updatedAt: iso(-90, 12),
    submittedBy: 'rajesh.kumar',
    submittedAt: iso(-175, 11),
    verifiedBy: 'mohan.v',
    verifiedAt: iso(-160, 14),
    approvedBy: 'priya.f',
    approvedAt: iso(-150, 16),
    comments: [
      { id: 'bc1', user: 'mohan.v', role: 'Verifier', message: 'Variances within acceptable range.', at: iso(-160, 14) },
    ],
    history: [
      { id: 'bh1', user: 'rajesh.kumar', role: 'Creator', action: 'Created Budget', at: iso(-180, 10) },
      { id: 'bh2', user: 'rajesh.kumar', role: 'Creator', action: 'Submitted for Verification', at: iso(-175, 11) },
      { id: 'bh3', user: 'mohan.v', role: 'Verifier', action: 'Verified & Forwarded to Approver', at: iso(-160, 14) },
      { id: 'bh4', user: 'priya.f', role: 'Finance', action: 'Approved', at: iso(-150, 16), detail: 'Locked' },
    ],
  },
  {
    id: 'BUD-2026-002',
    fy: 'FY 2025-26',
    name: 'College of Pharmacy — Operations',
    entityType: 'College',
    entityName: 'College of Pharmacy',
    version: 1,
    status: 'Submitted',
    heads: [
      { id: 'p-tada',  name: 'TA/DA',         allocated: 320000,  utilized: 0, reserved: 0, lastYearAmount: 280000 },
      { id: 'p-rem',   name: 'Remuneration',  allocated: 1450000, utilized: 0, reserved: 0, lastYearAmount: 1100000 },
      { id: 'p-eq',    name: 'Equipment',     allocated: 2200000, utilized: 0, reserved: 0, lastYearAmount: 1500000 },
      { id: 'p-util',  name: 'Utilities',     allocated: 580000,  utilized: 0, reserved: 0, lastYearAmount: 540000 },
    ],
    createdBy: 'sunita.rao',
    createdAt: iso(-12, 10),
    updatedAt: iso(-2, 14),
    submittedBy: 'sunita.rao',
    submittedAt: iso(-2, 14),
    comments: [
      { id: 'bc2', user: 'sunita.rao', role: 'Creator', message: 'Equipment up because of new lab setup.', at: iso(-2, 14) },
    ],
    history: [
      { id: 'bh5', user: 'sunita.rao', role: 'Creator', action: 'Created Budget', at: iso(-12, 10) },
      { id: 'bh6', user: 'sunita.rao', role: 'Creator', action: 'Submitted for Verification', at: iso(-2, 14) },
    ],
  },
  {
    id: 'BUD-2026-003',
    fy: 'FY 2025-26',
    name: 'Department of Anatomy — Annual',
    entityType: 'Department',
    entityName: 'Department of Anatomy',
    version: 1,
    status: 'Verified',
    heads: [
      { id: 'a-tada',  name: 'TA/DA',          allocated: 180000,  utilized: 0, reserved: 0, lastYearAmount: 165000 },
      { id: 'a-eq',    name: 'Equipment',      allocated: 950000,  utilized: 0, reserved: 0, lastYearAmount: 720000 },
      { id: 'a-amc',   name: 'AMC',            allocated: 240000,  utilized: 0, reserved: 0, lastYearAmount: 220000 },
      { id: 'a-mis',   name: 'Miscellaneous',  allocated: 60000,   utilized: 0, reserved: 0, lastYearAmount: 50000 },
    ],
    createdBy: 'sunita.rao',
    createdAt: iso(-20, 11),
    updatedAt: iso(-5, 16),
    submittedBy: 'sunita.rao',
    submittedAt: iso(-15, 12),
    verifiedBy: 'mohan.v',
    verifiedAt: iso(-5, 16),
    comments: [
      { id: 'bc3', user: 'mohan.v', role: 'Verifier', message: 'Equipment increase justified — new microscope.', at: iso(-5, 16) },
    ],
    history: [
      { id: 'bh7', user: 'sunita.rao', role: 'Creator', action: 'Created Budget', at: iso(-20, 11) },
      { id: 'bh8', user: 'sunita.rao', role: 'Creator', action: 'Submitted for Verification', at: iso(-15, 12) },
      { id: 'bh9', user: 'mohan.v', role: 'Verifier', action: 'Verified & Forwarded to Approver', at: iso(-5, 16) },
    ],
  },
  {
    id: 'BUD-2026-004',
    fy: 'FY 2025-26',
    name: 'Examination Section — Q4 Top-up',
    entityType: 'Department',
    entityName: 'Examination Section',
    version: 1,
    status: 'Sent Back',
    heads: [
      { id: 'e-rem',   name: 'Remuneration',  allocated: 850000, utilized: 0, reserved: 0, lastYearAmount: 600000 },
      { id: 'e-hon',   name: 'Honorarium',    allocated: 320000, utilized: 0, reserved: 0, lastYearAmount: 250000 },
      { id: 'e-tada',  name: 'TA/DA',         allocated: 90000,  utilized: 0, reserved: 0, lastYearAmount: 80000 },
    ],
    createdBy: 'meena.s',
    createdAt: iso(-10, 9),
    updatedAt: iso(-1, 11),
    submittedBy: 'meena.s',
    submittedAt: iso(-7, 10),
    comments: [
      { id: 'bc4', user: 'mohan.v', role: 'Verifier', message: 'Remuneration up 42% YoY — please justify with workload data.', at: iso(-1, 11) },
    ],
    history: [
      { id: 'bh10', user: 'meena.s', role: 'Creator', action: 'Created Budget', at: iso(-10, 9) },
      { id: 'bh11', user: 'meena.s', role: 'Creator', action: 'Submitted', at: iso(-7, 10) },
      { id: 'bh12', user: 'mohan.v', role: 'Verifier', action: 'Sent Back', at: iso(-1, 11), detail: 'Variance unexplained' },
    ],
  },
  {
    id: 'BUD-2026-005',
    fy: 'FY 2025-26',
    name: 'Estate & Maintenance — Capex',
    entityType: 'Department',
    entityName: 'Estate & Maintenance',
    version: 1,
    status: 'Draft',
    heads: [
      { id: 'm-eq',   name: 'Equipment', allocated: 0, utilized: 0, reserved: 0, lastYearAmount: 1200000 },
      { id: 'm-amc',  name: 'AMC',       allocated: 0, utilized: 0, reserved: 0, lastYearAmount: 480000 },
    ],
    createdBy: 'rajesh.kumar',
    createdAt: iso(-1, 10),
    updatedAt: iso(-1, 10),
    comments: [],
    history: [
      { id: 'bh13', user: 'rajesh.kumar', role: 'Creator', action: 'Created Budget', at: iso(-1, 10) },
    ],
  },
];

export const initialReservations: BudgetReservation[] = [
  { id: 'RSV-001', budgetId: 'BUD-2026-001', headName: 'TA/DA',     refType: 'BILL', refId: 'BILL-2026-0001', amount: 45200,  status: 'ACTIVE',   createdAt: iso(-3, 11) },
  { id: 'RSV-002', budgetId: 'BUD-2026-001', headName: 'Equipment', refType: 'BILL', refId: 'BILL-2026-0002', amount: 235000, status: 'ACTIVE',   createdAt: iso(-5, 11) },
  { id: 'RSV-003', budgetId: 'BUD-2026-001', headName: 'Remuneration', refType: 'BILL', refId: 'BILL-2026-0003', amount: 78000,  status: 'ACTIVE',   createdAt: iso(-7, 11) },
  { id: 'RSV-004', budgetId: 'BUD-2026-001', headName: 'Honorarium', refType: 'BILL', refId: 'BILL-2026-0004', amount: 12000,  status: 'CONSUMED', createdAt: iso(-15, 11), releasedAt: iso(-2, 12) },
  { id: 'RSV-005', budgetId: 'BUD-2026-001', headName: 'AMC',       refType: 'BILL', refId: 'BILL-2026-0006', amount: 92500,  status: 'ACTIVE',   createdAt: iso(-4, 11) },
  { id: 'RSV-006', budgetId: 'BUD-2026-001', headName: 'Utilities', refType: 'BILL', refId: 'BILL-2026-0005', amount: 184500, status: 'ACTIVE',   createdAt: iso(-1, 9) },
];

export const initialAllocations: BudgetAllocation[] = [
  { id: 'ALL-001', budgetId: 'BUD-2026-001', headName: 'Equipment',     targetEntityType: 'College',    targetEntityName: 'College of Pharmacy',     amount: 2200000, allocatedAt: iso(-90, 12), createdBy: 'priya.f' },
  { id: 'ALL-002', budgetId: 'BUD-2026-001', headName: 'Equipment',     targetEntityType: 'Department', targetEntityName: 'Department of Anatomy',   amount: 950000,  allocatedAt: iso(-90, 12), createdBy: 'priya.f' },
  { id: 'ALL-003', budgetId: 'BUD-2026-001', headName: 'Remuneration',  targetEntityType: 'Department', targetEntityName: 'Examination Section',     amount: 850000,  allocatedAt: iso(-85, 14), createdBy: 'priya.f' },
];

export const initialAdjustments: BudgetAdjustment[] = [
  { id: 'ADJ-001', budgetId: 'BUD-2026-001', fromHead: 'Miscellaneous', toHead: 'Equipment', amount: 200000, type: 'TRANSFER', reason: 'Q3 microscope purchase', status: 'APPROVED', createdBy: 'priya.f', createdAt: iso(-45, 11), approvedBy: 'priya.f', approvedAt: iso(-44, 12) },
  { id: 'ADJ-002', budgetId: 'BUD-2026-001', fromHead: 'TA/DA',         toHead: 'AMC',       amount: 80000,  type: 'TRANSFER', reason: 'Software AMC mid-year renewal', status: 'PENDING', createdBy: 'priya.f', createdAt: iso(-2, 11) },
];

/* ============== Receipts (Incoming Payments) — seed across statuses ============== */

export const receiptAccountHeads = [
  'Tuition Fees',
  'Exam Fees',
  'Affiliation Fees',
  'Lab Fees',
  'Library Fees',
  'Hostel Fees',
  'Vendor Refund',
  'Misc. Income',
];

export const initialReceipts: Receipt[] = [
  {
    id: 'RCPT-001',
    receiptNumber: 'RCT-2026-0001',
    receiptDate: iso(-1, 11),
    entityType: 'College',
    entityName: 'College of Pharmacy',
    sourceType: 'Student',
    sourceReferenceId: 'STU-2026-1284',
    payerName: 'Aarti Sharma',
    payerIdentifier: 'PHARM-2026-128',
    paymentMode: 'UPI',
    transactionReference: 'UPI-9923810098',
    bankName: 'HDFC Bank',
    paymentDate: iso(-1, 11),
    amount: 85000,
    lines: [
      { id: 'rl-1', accountHead: 'Tuition Fees', amount: 75000, remarks: 'Sem 3 fees' },
      { id: 'rl-2', accountHead: 'Lab Fees', amount: 10000 },
    ],
    status: 'Submitted',
    createdBy: 'rajesh.kumar',
    createdAt: iso(-1, 10),
    updatedAt: iso(-1, 11),
    submittedBy: 'rajesh.kumar',
    submittedAt: iso(-1, 11),
    comments: [],
    history: [
      { id: 'rh1', user: 'rajesh.kumar', role: 'Creator', action: 'Created Receipt', at: iso(-1, 10) },
      { id: 'rh2', user: 'rajesh.kumar', role: 'Creator', action: 'Submitted for Verification', at: iso(-1, 11) },
    ],
  },
  {
    id: 'RCPT-002',
    receiptNumber: 'RCT-2026-0002',
    receiptDate: iso(-3, 14),
    entityType: 'University',
    entityName: 'RGUHS HQ',
    sourceType: 'External',
    payerName: 'KMC Affiliation Trust',
    payerIdentifier: 'TRUST-AAACK1234E',
    paymentMode: 'RTGS',
    transactionReference: 'RTGS-2026-44521',
    bankName: 'State Bank of India',
    paymentDate: iso(-3, 13),
    amount: 1250000,
    lines: [{ id: 'rl-3', accountHead: 'Affiliation Fees', amount: 1250000, remarks: 'Annual affiliation' }],
    status: 'Verified',
    createdBy: 'sunita.rao',
    createdAt: iso(-4, 10),
    updatedAt: iso(-2, 16),
    submittedBy: 'sunita.rao',
    submittedAt: iso(-3, 14),
    verifiedBy: 'mohan.v',
    verifiedAt: iso(-2, 16),
    comments: [
      { id: 'rc1', user: 'mohan.v', role: 'Verifier', message: 'Bank ref matched. Forwarding for approval.', at: iso(-2, 16) },
    ],
    history: [
      { id: 'rh3', user: 'sunita.rao', role: 'Creator', action: 'Created Receipt', at: iso(-4, 10) },
      { id: 'rh4', user: 'sunita.rao', role: 'Creator', action: 'Submitted', at: iso(-3, 14) },
      { id: 'rh5', user: 'mohan.v', role: 'Verifier', action: 'Verified & Forwarded to Approver', at: iso(-2, 16) },
    ],
  },
  {
    id: 'RCPT-003',
    receiptNumber: 'RCT-2026-0003',
    receiptDate: iso(-7, 9),
    entityType: 'Department',
    entityName: 'Examination Section',
    sourceType: 'Student',
    sourceReferenceId: 'BATCH-EXAM-Q4',
    payerName: 'Karthik R',
    payerIdentifier: 'MED-2026-441',
    paymentMode: 'NEFT',
    transactionReference: 'NEFT-2026-44811',
    bankName: 'ICICI Bank',
    paymentDate: iso(-7, 9),
    amount: 18000,
    lines: [{ id: 'rl-4', accountHead: 'Exam Fees', amount: 18000, remarks: 'Final year exam' }],
    status: 'Confirmed',
    createdBy: 'meena.s',
    createdAt: iso(-8, 8),
    updatedAt: iso(-5, 11),
    submittedBy: 'meena.s',
    submittedAt: iso(-7, 9),
    verifiedBy: 'mohan.v',
    verifiedAt: iso(-6, 14),
    approvedBy: 'lakshmi.a',
    approvedAt: iso(-6, 16),
    confirmedBy: 'priya.f',
    confirmedAt: iso(-5, 11),
    comments: [],
    history: [
      { id: 'rh6', user: 'meena.s', role: 'Creator', action: 'Submitted', at: iso(-7, 9) },
      { id: 'rh7', user: 'mohan.v', role: 'Verifier', action: 'Verified', at: iso(-6, 14) },
      { id: 'rh8a', user: 'lakshmi.a', role: 'Approver', action: 'Approved & Forwarded to Finance Officer', at: iso(-6, 16) },
      { id: 'rh8b', user: 'priya.f', role: 'Finance', action: 'Confirmed (Finance Officer review)', at: iso(-5, 11) },
    ],
  },
  {
    id: 'RCPT-004',
    receiptNumber: 'RCT-2026-0004',
    receiptDate: iso(-2, 16),
    entityType: 'College',
    entityName: 'College of Medicine',
    sourceType: 'Student',
    payerName: 'Pooja Iyer',
    payerIdentifier: 'MED-2026-552',
    paymentMode: 'UPI',
    transactionReference: 'UPI-9923810098', // duplicate of RCPT-001 — flagged
    bankName: 'HDFC Bank',
    paymentDate: iso(-2, 16),
    amount: 85000,
    lines: [{ id: 'rl-5', accountHead: 'Tuition Fees', amount: 85000 }],
    status: 'Submitted',
    createdBy: 'rajesh.kumar',
    createdAt: iso(-2, 15),
    updatedAt: iso(-2, 16),
    submittedBy: 'rajesh.kumar',
    submittedAt: iso(-2, 16),
    duplicateFlag: true,
    duplicateMatchScore: 'HIGH',
    duplicateReason: 'Same transaction reference and amount',
    comments: [],
    history: [
      { id: 'rh9', user: 'rajesh.kumar', role: 'Creator', action: 'Created Receipt', at: iso(-2, 15) },
      { id: 'rh10', user: 'rajesh.kumar', role: 'Creator', action: 'Submitted', at: iso(-2, 16) },
    ],
  },
  {
    id: 'RCPT-005',
    receiptNumber: 'RCT-2026-0005',
    receiptDate: iso(-1, 13),
    entityType: 'Department',
    entityName: 'Central Library',
    sourceType: 'Vendor',
    payerName: 'EduSoft Solutions',
    payerIdentifier: 'AAACE7843K',
    paymentMode: 'CHEQUE',
    transactionReference: 'CHQ-001284',
    bankName: 'Yes Bank',
    paymentDate: iso(-1, 13),
    instrumentDetails: 'Cheque No 001284 dt 28-Apr-26',
    amount: 12500,
    lines: [{ id: 'rl-6', accountHead: 'Vendor Refund', amount: 12500, remarks: 'AMC excess refund' }],
    status: 'Sent Back',
    createdBy: 'sunita.rao',
    createdAt: iso(-2, 9),
    updatedAt: iso(-1, 14),
    submittedBy: 'sunita.rao',
    submittedAt: iso(-1, 13),
    comments: [
      { id: 'rc2', user: 'mohan.v', role: 'Verifier', message: 'Cheque date does not match. Please verify and resubmit.', at: iso(-1, 14) },
    ],
    history: [
      { id: 'rh11', user: 'sunita.rao', role: 'Creator', action: 'Submitted', at: iso(-1, 13) },
      { id: 'rh12', user: 'mohan.v', role: 'Verifier', action: 'Sent Back', at: iso(-1, 14), detail: 'Cheque date mismatch' },
    ],
  },
  {
    id: 'RCPT-006',
    receiptNumber: 'RCT-2026-0006',
    receiptDate: iso(-1, 10),
    entityType: 'Department',
    entityName: 'Office of the Registrar',
    sourceType: 'Other',
    payerName: 'RGUHS Convocation Fund',
    payerIdentifier: 'INTERNAL-CONV-26',
    paymentMode: 'NEFT',
    transactionReference: 'NEFT-2026-44900',
    bankName: 'Canara Bank',
    paymentDate: iso(-1, 10),
    amount: 350000,
    lines: [{ id: 'rl-7', accountHead: 'Misc. Income', amount: 350000 }],
    status: 'Draft',
    createdBy: 'rajesh.kumar',
    createdAt: iso(-1, 10),
    updatedAt: iso(-1, 10),
    comments: [],
    history: [
      { id: 'rh13', user: 'rajesh.kumar', role: 'Creator', action: 'Created Receipt', at: iso(-1, 10) },
    ],
  },
  // Approved by Approver — waiting for Finance Officer's final review
  {
    id: 'RCPT-007',
    receiptNumber: 'RCT-2026-0007',
    receiptDate: iso(-4, 9),
    entityType: 'College',
    entityName: 'College of Nursing',
    sourceType: 'Student',
    sourceReferenceId: 'NRS-2026-091',
    payerName: 'Sneha Bhat',
    payerIdentifier: 'NRS-2026-091',
    paymentMode: 'NEFT',
    transactionReference: 'NEFT-2026-49870',
    bankName: 'Axis Bank',
    paymentDate: iso(-4, 9),
    amount: 65000,
    lines: [
      { id: 'rl-8', accountHead: 'Tuition Fees', amount: 60000, remarks: 'Sem 5 fees' },
      { id: 'rl-9', accountHead: 'Library Fees', amount: 5000 },
    ],
    status: 'Approved',
    createdBy: 'sunita.rao',
    createdAt: iso(-5, 10),
    updatedAt: iso(-2, 14),
    submittedBy: 'sunita.rao',
    submittedAt: iso(-4, 9),
    verifiedBy: 'mohan.v',
    verifiedAt: iso(-3, 11),
    approvedBy: 'lakshmi.a',
    approvedAt: iso(-2, 14),
    comments: [
      { id: 'rc3', user: 'mohan.v', role: 'Verifier', message: 'All fields look good. Forwarding.', at: iso(-3, 11) },
      { id: 'rc4', user: 'lakshmi.a', role: 'Approver', message: 'Approved. Awaiting Finance Officer review.', at: iso(-2, 14) },
    ],
    history: [
      { id: 'rh14', user: 'sunita.rao', role: 'Creator', action: 'Submitted', at: iso(-4, 9) },
      { id: 'rh15', user: 'mohan.v', role: 'Verifier', action: 'Verified & Forwarded to Approver', at: iso(-3, 11) },
      { id: 'rh16', user: 'lakshmi.a', role: 'Approver', action: 'Approved & Forwarded to Finance Officer', at: iso(-2, 14) },
    ],
  },
];

export const initialReceiptCancellations: ReceiptCancellationRequest[] = [];

export const initialReconBatches: ReconciliationBatch[] = [
  {
    batchId: 'BATCH-2026-04',
    fileName: 'sbi-stmt-apr-2026.csv',
    uploadedAt: iso(-2, 10),
    uploadedBy: 'arvind.p',
    totalTransactions: 24,
    matchedCount: 20,
    unmatchedCount: 3,
    exceptionsCount: 1,
    status: 'Matching',
    transactions: [
      { id: 't1', systemTxnId: 'TXN-1001', bankTxnId: 'BNK-9001', amountSystem: 45200, amountBank: 45200, date: iso(-2, 10), reference: 'BILL-2026-0001', matchStatus: 'Matched' },
      { id: 't2', systemTxnId: 'TXN-1002', bankTxnId: 'BNK-9002', amountSystem: 12000, amountBank: 12000, date: iso(-3, 10), reference: 'BILL-2026-0004', matchStatus: 'Matched' },
      { id: 't3', systemTxnId: 'TXN-1003', bankTxnId: '—', amountSystem: 78000, amountBank: 0, date: iso(-1, 10), reference: 'BILL-2026-0003', matchStatus: 'Unmatched', issueType: 'Missing' },
      { id: 't4', systemTxnId: 'TXN-1004', bankTxnId: 'BNK-9004', amountSystem: 184500, amountBank: 185000, date: iso(-2, 11), reference: 'BILL-2026-0005', matchStatus: 'Exception', issueType: 'Amount Mismatch' },
      { id: 't5', systemTxnId: 'TXN-1005', bankTxnId: 'BNK-9005', amountSystem: 92500, amountBank: 92500, date: iso(-2, 12), reference: 'BILL-2026-0006', matchStatus: 'Matched' },
    ],
  },
  {
    batchId: 'BATCH-2026-03',
    fileName: 'hdfc-stmt-mar-2026.csv',
    uploadedAt: iso(-30, 9),
    uploadedBy: 'arvind.p',
    totalTransactions: 31,
    matchedCount: 31,
    unmatchedCount: 0,
    exceptionsCount: 0,
    status: 'Reconciled',
    transactions: [],
  },
];

export const initialAuditLogs: AuditLog[] = [
  { id: 'AL-1', at: iso(-3, 11), user: 'rajesh.kumar', role: 'Creator', action: 'Submitted Bill', module: 'Bills', target: 'BILL-2026-0001' },
  { id: 'AL-2', at: iso(-2, 16), user: 'mohan.v', role: 'Verifier', action: 'Verified Bill', module: 'Bills', target: 'BILL-2026-0002' },
  { id: 'AL-3', at: iso(-1, 11), user: 'priya.f', role: 'Finance', action: 'Approved Bill', module: 'Bills', target: 'BILL-2026-0003', detail: 'Within budget' },
  { id: 'AL-4', at: iso(-2, 12), user: 'arvind.p', role: 'Payment', action: 'Paid via NEFT', module: 'Payments', target: 'BILL-2026-0004' },
  { id: 'AL-5', at: iso(-1, 15), user: 'mohan.v', role: 'Verifier', action: 'Sent Back Bill', module: 'Bills', target: 'BILL-2026-0006', detail: 'GSTIN missing' },
  { id: 'AL-6', at: iso(-2, 10), user: 'arvind.p', role: 'Payment', action: 'Uploaded Bank Statement', module: 'Reconciliation', target: 'BATCH-2026-04' },
  { id: 'AL-7', at: iso(-150, 16), user: 'priya.f', role: 'Finance', action: 'Approved Budget', module: 'Budgets', target: 'BUD-2026-001' },
  { id: 'AL-8', at: iso(-5, 16), user: 'mohan.v', role: 'Verifier', action: 'Verified Budget', module: 'Budgets', target: 'BUD-2026-003' },
  { id: 'AL-9', at: iso(-2, 14), user: 'sunita.rao', role: 'Creator', action: 'Submitted Budget', module: 'Budgets', target: 'BUD-2026-002' },
  { id: 'AL-10', at: iso(-1, 11), user: 'mohan.v', role: 'Verifier', action: 'Sent Back Budget', module: 'Budgets', target: 'BUD-2026-004', detail: 'Variance unexplained' },
];

export const roleUsers: Record<string, string> = {
  Creator: 'rajesh.kumar',
  Verifier: 'mohan.v',
  Approver: 'lakshmi.a',
  Finance: 'priya.f',
  Payment: 'arvind.p',
  Auditor: 'audit.admin',
};

export const departments = [
  'Department of Pharmacology',
  'Department of Anatomy',
  'Examination Section',
  'Estate & Maintenance',
  'Central Library',
  'Office of the Registrar',
];

export const billTypes = [
  'TA/DA Reimbursement',
  'Vendor Payment',
  'Remuneration',
  'Honorarium',
  'Utility Bill',
  'Equipment Purchase',
];

export const accountHeads = [
  'TA/DA',
  'Remuneration',
  'Honorarium',
  'Equipment',
  'AMC',
  'Utilities',
  'Miscellaneous',
  'Travel',
  'Stationery',
  'Software',
];

export const entityList: { type: 'University' | 'College' | 'Department'; name: string }[] = [
  { type: 'University', name: 'RGUHS HQ' },
  { type: 'College', name: 'College of Pharmacy' },
  { type: 'College', name: 'College of Medicine' },
  { type: 'College', name: 'College of Nursing' },
  { type: 'College', name: 'College of Dentistry' },
  { type: 'Department', name: 'Department of Pharmacology' },
  { type: 'Department', name: 'Department of Anatomy' },
  { type: 'Department', name: 'Examination Section' },
  { type: 'Department', name: 'Estate & Maintenance' },
  { type: 'Department', name: 'Central Library' },
  { type: 'Department', name: 'Office of the Registrar' },
];

export const fiscalYears = ['FY 2024-25', 'FY 2025-26', 'FY 2026-27'];
